name: arbor___offsets___mvp___v_15
description: Arbor Carbon Offset

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  #sdk: ">=2.0.0-dev.68.0 <3.0.0"
  #sdk: ">=2.10.0 <3.0.0"
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  characters: ^1.0.0
  flutter:
    sdk: flutter
  carousel_slider: ^2.2.1
  auto_size_text: ^2.1.0
  percent_indicator: "^2.1.5"
  dots_indicator: ^1.2.0
  webview_flutter: 2.0.4

  # wave:
  # git: 
    # url: git://github.com/searchy2/wave.git
  chewie: ^1.0.0
  #video_player: ^2.0.0
  flutter_html: ^2.0.0
  

  # Database
  firebase: ^9.0.1
  #firebase_core: ^0.5.2+1
  firebase_core: ^1.1.0
  # User Auth
  #firebase_auth: ^0.18.3+1
  #firebase_auth: ^1.1.3
  firebase_auth: ^1.2.0
  firebase_crashlytics: "^2.0.7"
  # Analytics
  #firebase_analytics: ^6.2.0
  #firebase_analytics: ^8.0.3
  firebase_analytics: ^8.1.0
  # Performance
  #firebase_performance: ^0.4.0
  firebase_performance: ^0.7.0+2
  #firebase_messaging: ^6.0.16
  #firebase_messaging: ^7.0.3
  firebase_messaging: ^10.0.0
  plugin_platform_interface: ^2.0.0

  # Cloud Storage
  #cloud_firestore: ^0.14.1
  #cloud_firestore: ^2.0.0
  cloud_firestore: <2.0.0
  
  # Stripe Payment
  #stripe_payment: ^1.0.8
  stripe_payment: ^1.1.0
  #flutter_stripe: ^1.0.0+3

  # http
  #http: ^0.12.0+4
  http: ^0.13.3

  # Progress HUD
  modal_progress_hud: ^0.1.3

  #show a URL
  #url_launcher: ^5.7.8
  url_launcher: ^6.0.3

  # flutter_html: ^1.0.2

  # internationalization: ^3.0.1+1

  provider: ^5.0.0

  package_info: ^0.4.0+16
  
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2 #^0.1.2

  path_provider: ^2.0.1 #^1.6.24

  # for sharing on social media, etc
  share: ^2.0.1

  shared_preferences: ^2.0.6

dependency_overrides:
  flutter_svg: ^0.22.0

dev_dependencies:
  flutter_test:
    sdk: flutter

analyzer:
  enable-experiment:
    - control-flow-collections
    
# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  
  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - assets/images/a_dot_burr.jpeg
  #  - assets/images/a_dot_ham.jpeg
  
  # or to include all assets from a directory do this:
  # assets:
  #   - assets/images/
  
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.
  assets:
    - assets/images/
  
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: assets/fonts/Schyler-Regular.ttf
  #       - asset: assets/fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: assets/fonts/TrajanPro.ttf
  #       - asset: assets/fonts/TrajanPro_Bold.ttf
  #         weight: 700
  
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Medium.ttf
          weight: 500
        - asset: assets/fonts/Raleway-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Raleway-Black.ttf
          weight: 900
        - asset: assets/fonts/Raleway-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Raleway-Bold.ttf
          weight: 700
        - asset: assets/fonts/Raleway-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Raleway-Light.ttf
          weight: 300
    #- family: SF Compact Display
    #  fonts:
    #    - asset: assets/fonts/SF-Compact-Display-Light.otf
    #      weight: 300
    #- family: Montserrat
      # fonts:
      #   - asset: assets/fonts/Montserrat-SemiBold.ttf
      #     weight: 600
      #   - asset: assets/fonts/Montserrat-Medium.ttf
      #     weight: 500
    - family: .AppleSystemUIFont
      fonts:
        - asset: assets/fonts/SFNS.ttf